name: Validate Automation Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate automation-config.json Exists
        run: |
          if [ ! -f "automation-config.json" ]; then
            echo "❌ automation-config.json is missing!"
            exit 1
          else
            echo "✅ automation-config.json found."
          fi

      - name: Validate JSON Syntax
        run: |
          cat automation-config.json | jq .
