name: Yarn Install and Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Linter
        run: yarn lint
